parameters:
  # Test only the Release build by default.
- name: ReleaseBuildTarget
  displayName: 'Build which target for Release?'
  type: string
  values: [ Build, Integration, UnitTest ]
  default: UnitTest
- name: OtherBuildTarget
  displayName: 'Build which target for Debug/CodeAnalysis?'
  type: string
  values: [ Build, Integration, UnitTest ]
  default: Build

variables:
- name: DOTNET_CLI_TELEMETRY_OPTOUT
  value: 1
- name: DOTNET_NOLOGO
  value: 1
  # Run CodeQL3000 tasks in a separate internal pipeline; not needed here.
- name: Codeql.SkipTaskAutoInjection
  value: true

trigger: [main]
pr: ['*']

stages:
- stage: build
  displayName: Build
  jobs:
  - template: /eng/templates/default-build.yml
    parameters:
      ReleaseBuildTarget: ${{ parameters.ReleaseBuildTarget }}
      OtherBuildTarget: ${{ parameters.OtherBuildTarget }}
